# .github/workflows/e2e-playwright.yml
name: E2E Playwright Tests (Staging)

on:
  push:
    branches: [master, staging]
  pull_request:
    types: [opened, synchronize, reopened]

env:
  # Environment for your ConfigLoader.ts
  TARGET_ENV: staging

  # Base URL and start path stored as secrets to avoid pushing to repo
  BASE_URL: ${{ secrets.BASE_URL }}
  START_PATH: ${{ secrets.START_PATH }}

  # Staging credentials
  STAGING_USER_EMAIL: ${{ secrets.STAGING_TEST_EMAIL }}
  STAGING_USER_PASS: ${{ secrets.STAGING_TEST_PASS }}

jobs:
  e2e:
    name: Run Playwright E2E Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          npm ci
          npx playwright install --with-deps

      - name: Run Playwright tests (staging)
        run: npx playwright test --reporter=html,line

      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 7
